data:
  X_train: './data/Train/X_train.txt'
  y_train: './data/Train/y_train.txt'
  X_test: './data/Test/X_test.txt'
  y_test: './data/Test/y_test.txt'
  features: './data/features.txt'
  activity_labels: './data/activity_labels.txt'
pipeline:
  transformer:
    normalize:
      norm: ['l2']
    subset: './subset_test.txt'
  classifier:
    logistic:
      penalty: ['l2']
      max_iter: [100]
  grid:
    cv: 2
    scoring: 'f1_weighted'