data:
  X_train: './data/Train/X_train.txt'
  y_train: './data/Train/y_train.txt'
  X_test: './data/Test/X_test.txt'
  y_test: './data/Test/y_test.txt'
  features: './data/features.txt'
  activity_labels: './data/activity_labels.txt'
pipeline:
  transformer:
    normalize:
      norm: ['l2']
    subset: './subsets/xgb_var_subset.txt'
  classifier:
    logistic:
      penalty: ['l1', 'l2', 'elasticnet']
      max_iter: [1000, 10000]
      n_jobs: [1]
      early_stopping: [True]
      loss: ['log']
      learning_rate: ['optimal']
      class_weight: ['balanced']
      shuffle: [True]
      random_state: [0]
  grid:
    cv: 2
    scoring: 'f1_weighted'
    n_jobs: 2
    verbose: 2